import DobotDllType as dType


def main():
	api = dType.load()
	# Connect Dobot
	state = dType.ConnectDobot(api, "", 115200)[0]

	if state == dType.DobotConnect.DobotConnect_NoError) + "\n")
		self.__dobot = DobotMagician(api)
		print('Dobot Magician connected succesfully!')

		print("GetMarlinVersion(api)")
		print(str(dType.GetMarlinVersion(api)) + "\n")
		print("GetQueuedCmdCurrentIndex(api)")
		print(str(dType.GetQueuedCmdCurrentIndex(api)) + "\n")
		print("GetQueuedCmdMotionFinish(api)")
		print(str(dType.GetQueuedCmdMotionFinish(api)) + "\n")
		print("GetDeviceSN(api)")
		print(str(dType.GetDeviceSN(api)) + "\n")
		print("GetDeviceName(api)")
		print(str(dType.GetDeviceName(api)) + "\n")
		print("GetDeviceVersion(api)")
		print(str(dType.GetDeviceVersion(api)) + "\n")
		print("GetDeviceWithL(api)")
		print(str(dType.GetDeviceWithL(api)) + "\n")
		print("GetDeviceTime(api)")
		print(str(dType.GetDeviceTime(api)) + "\n")
		print("GetDeviceID(api)")
		print(str(dType.GetDeviceID(api)) + "\n")
		print("GetDeviceInfo(api)")
		print(str(dType.GetDeviceInfo(api)) + "\n")
		print("GetPose(api)")
		print(str(dType.GetPose(api)) + "\n")
		print("GetPoseL(api)")
		print(str(dType.GetPoseL(api)) + "\n")
		print("GetKinematics(api)")
		print(str(dType.GetKinematics(api)) + "\n")
		print("GetAlarmsState(api,  10)")
		print(str(dType.GetAlarmsState(api,  10)) + "\n")
		print("GetUserParams(api)")
		print(str(dType.GetUserParams(api)) + "\n")
		print("GetHOMEParams(api)")
		print(str(dType.GetHOMEParams(api)) + "\n")
		print("GetAutoLevelingResult(api)")
		print(str(dType.GetAutoLevelingResult(api)) + "\n")
		print("GetArmOrientation(api)")
		print(str(dType.GetArmOrientation(api)) + "\n")
		print("GetHHTTrigMode(api)")
		print(str(dType.GetHHTTrigMode(api)) + "\n")
		print("GetHHTTrigOutputEnabled(api)")
		print(str(dType.GetHHTTrigOutputEnabled(api)) + "\n")
		print("GetHHTTrigOutput(api)")
		print(str(dType.GetHHTTrigOutput(api)) + "\n")
		print("GetEndEffectorParams(api)")
		print(str(dType.GetEndEffectorParams(api)) + "\n")
		print("GetEndEffectorLaser(api)")
		print(str(dType.GetEndEffectorLaser(api)) + "\n")
		print("GetEndEffectorSuctionCup(api)")
		print(str(dType.GetEndEffectorSuctionCup(api)) + "\n")
		print("GetEndEffectorGripper(api)")
		print(str(dType.GetEndEffectorGripper(api)) + "\n")
		print("GetJOGJointParams(api)")
		print(str(dType.GetJOGJointParams(api)) + "\n")
		print("GetJOGCoordinateParams(api)")
		print(str(dType.GetJOGCoordinateParams(api)) + "\n")
		print("GetJOGLParams(api)")
		print(str(dType.GetJOGLParams(api)) + "\n")
		print("GetJOGCommonParams(api)")
		print(str(dType.GetJOGCommonParams(api)) + "\n")
		print("GetPTPJointParams(api)")
		print(str(dType.GetPTPJointParams(api)) + "\n")
		print("GetPTPCoordinateParams(api)")
		print(str(dType.GetPTPCoordinateParams(api)) + "\n")
		print("GetPTPLParams(api)")
		print(str(dType.GetPTPLParams(api)) + "\n")
		print("GetPTPJumpParams(api)")
		print(str(dType.GetPTPJumpParams(api)) + "\n")
		print("GetPTPCommonParams(api)")
		print(str(dType.GetPTPCommonParams(api)) + "\n")
		print("GetCPRHoldEnable(api)")
		print(str(dType.GetCPRHoldEnable(api)) + "\n")
		print("GetCPParams(api)")
		print(str(dType.GetCPParams(api)) + "\n")
		print("GetCPCommonParams(api)")
		print(str(dType.GetCPCommonParams(api)) + "\n")
		print("GetARCParams(api)")
		print(str(dType.GetARCParams(api)) + "\n")
		print("GetARCCommonParams(api)")
		print(str(dType.GetARCCommonParams(api)) + "\n")
		#print("GetIOMultiplexing(api,  addr)")
		#print(str(dType.GetIOMultiplexing(api,  addr)) + "\n")
		#print("GetIODO(api,  addr)")
		#print(str(dType.GetIODO(api,  addr)) + "\n")
		#print("GetIOPWM(api,  addr)")
		#print(str(dType.GetIOPWM(api,  addr)) + "\n")
		#print("GetIODI(api, addr)")
		#print(str(dType.GetIODI(api, addr)) + "\n")
		#print("GetIOADC(api, addr)")
		#print(str(dType.GetIOADC(api, addr)) + "\n")
		print("GetAngleSensorStaticError(api)")
		print(str(dType.GetAngleSensorStaticError(api)) + "\n")
		print("GetAngleSensorCoef(api)")
		print(str(dType.GetAngleSensorCoef(api)) + "\n")
		print("GetBaseDecoderStaticError(api)")
		print(str(dType.GetBaseDecoderStaticError(api)) + "\n")
		print("GetWIFIConnectStatus(api)")
		print(str(dType.GetWIFIConnectStatus(api)) + "\n")
		print("GetWIFIConfigMode(api)")
		print(str(dType.GetWIFIConfigMode(api)) + "\n")
		print("GetWIFISSID(api)")
		print(str(dType.GetWIFISSID(api)) + "\n")
		print("GetWIFIPassword(api)")
		print(str(dType.GetWIFIPassword(api)) + "\n")
		print("GetWIFIIPAddress(api)")
		print(str(dType.GetWIFIIPAddress(api)) + "\n")
		print("GetWIFINetmask(api)")
		print(str(dType.GetWIFINetmask(api)) + "\n")
		print("GetWIFIGateway(api)")
		print(str(dType.GetWIFIGateway(api)) + "\n")
		print("GetWIFIDNS(api)")
		print(str(dType.GetWIFIDNS(api)) + "\n")
		print("GetColorSensor(api)")
		print(str(dType.GetColorSensor(api)) + "\n")
		print("GetInfraredSensor(api, infraredPort)")
		print(str(dType.GetInfraredSensor(api, infraredPort)) + "\n")
		print("GetUART4PeripheralsType(api)")
		print(str(dType.GetUART4PeripheralsType(api)) + "\n")
		print("GetDeviceVersionEx(api)")
		print(str(dType.GetDeviceVersionEx(api)) + "\n")
		print("GetPoseEx(api,  index)")
		print(str(dType.GetPoseEx(api,  index)) + "\n")
		print("GetColorSensorEx(api,  index)")
		print(str(dType.GetColorSensorEx(api,  index)) + "\n")
		print("GetUpgradeFWReadyCmd(api,fwSize, md5)")
		print(str(dType.GetUpgradeFWReadyCmd(api,fwSize, md5)) + "\n")
		print("GetMotorMode(api)")
		print(str(dType.GetMotorMode(api)) + "\n")
		#print("GetIOMultiplexingExt(api, addr)")
		#print(str(dType.GetIOMultiplexingExt(api, addr)) + "\n")
		#print("GetIOADCExt(api, addr)")
		#print(str(dType.GetIOADCExt(api, addr)) + "\n")
		#print("GetIOPWMExt(api, addr)")
		#print(str(dType.GetIOPWMExt(api, addr)) + "\n")
		#print("GetIODIExt(api, addr)")
		#print(str(dType.GetIODIExt(api, addr)) + "\n")
		#print("GetIODOExt(api, addr)")
		#print(str(dType.GetIODOExt(api, addr)) + "\n")
		#print("GetInfraredSensorExt(api, infraredPort)")
		#print(str(dType.GetInfraredSensorExt(api, infraredPort)) + "\n")
		print("GetColorSensorExt(api, index)")
		print(str(dType.GetColorSensorExt(api, index)) + "\n")
		print("GetSeeedColorSensorExt(api)")
		print(str(dType.GetSeeedColorSensorExt(api)) + "\n")
		print("GetSeeedDistanceSensorExt(api, SeeedPort)")
		print(str(dType.GetSeeedDistanceSensorExt(api, SeeedPort)) + "\n")
		print("GetSeeedTempSensorExt(api)")
		print(str(dType.GetSeeedTempSensorExt(api)) + "\n")
		print("GetSeeedLightSensorExt(api)")
		print(str(dType.GetSeeedLightSensorExt(api)) + "\n")
		print("GetLostStepEnableAndParamsCmd(api)")
		print(str(dType.GetLostStepEnableAndParamsCmd(api)) + "\n")
		print("GetEndEffectorType(api)")
		print(str(dType.GetEndEffectorType(api)) + "\n")
		print("GetServoAngle(api, servoId)")
		print(str(dType.GetServoAngle(api, servoId)) + "\n")
		print("GetArmSpeedRatio(api, paramsMode=0)")
		print(str(dType.GetArmSpeedRatio(api, paramsMode=0)) + "\n")
		print("GetLSpeedRatio(api, paramsMode=0)")
		print(str(dType.GetLSpeedRatio(api, paramsMode=0)) + "\n")
		return 0
	else:
		print("Couldn't connect with a Dobot Magician device")
		return 1

if __name__ == '__main__':
	main()
